# Cloudflare Pages 配置文件
name = "nuxt-template"
compatibility_date = "2024-10-28"
compatibility_flags = ["nodejs_compat"]

# Pages 配置
pages_build_output_dir = ".output/public"

# 环境变量
[vars]
# 在 Cloudflare Pages 中设置的环境变量
# NITRO_PRESET = "cloudflare-pages"
# NODE_VERSION = "20"

# 开发环境配置
[env.development]
name = "nuxt-template-dev"

# 生产环境配置
[env.production]
name = "nuxt-template-prod"